name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for Changesets
      pull-requests: write # Required for Changesets
      id-token: write # Required for OIDC authentication with JSR

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true

      - name: Check formatting
        run: deno fmt --check

      - name: Lint code
        run: deno lint

      - name: Type check
        run: deno task check

      - name: Publish to JSR
        run: deno publish
